-- Wise Pro Academy — limpeza de citacao de secao nos enunciados do IRC
-- Total: 91  (NAO altera resposta/alternativas/explicacao)
BEGIN;
UPDATE public.quiz_questions SET question = 'What is the minimum uniformly distributed live load for a habitable attic and attics served with a fixed stairway, as well as for sleeping rooms?' WHERE id = 'irc-005' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What is the minimum uniformly distributed live load for living areas (non-sleeping habitable rooms such as a living room or kitchen)?' WHERE id = 'irc-006' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What is the maximum stud spacing for a 2x4 stud in an exterior bearing wall supporting a roof, ceiling, and one floor above, at the common 10-foot stud height?' WHERE id = 'irc-013' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Under the 2021 IRC, what is the minimum thickness/class of the vapor retarder required between a concrete slab-on-grade floor and the base course or subgrade?' WHERE id = 'irc-018' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The garage side of a wall separating the garage from the residence (and attics) must be protected with at least what material?' WHERE id = 'irc-038' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Which of the following is a required fireblocking location?' WHERE id = 'irc-041' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Which of the following is an approved fireblocking material?' WHERE id = 'irc-042' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What is the minimum acceptable draftstopping material thickness for gypsum board?' WHERE id = 'irc-044' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Smoke alarms are required in all of the following locations EXCEPT:' WHERE id = 'irc-045' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Carbon monoxide alarms are required for new dwellings under which condition?' WHERE id = 'irc-047' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What is the minimum ceiling height for habitable spaces and hallways?' WHERE id = 'irc-058' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Window fall protection is required when the top of an operable window sill is less than 24 inches above the finished floor AND the opening is more than what distance above the exterior finished grade?' WHERE id = 'irc-061' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The connection of a top or sole plate to a stud by end nailing requires how many fasteners?' WHERE id = 'irc-067' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What is the minimum gypsum board thickness for a ceiling with framing spaced 16 inches on center where a water-based texture is applied?' WHERE id = 'irc-074' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Approved corrosion-resistant flashing must be applied to exterior walls in which of the following locations?' WHERE id = 'irc-075' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'In existing dwellings undergoing alterations or repairs, when are smoke alarms required to be added even without other work?' WHERE id = 'irc-077' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What is the minimum nominal size for a steel pipe column used to support beams or girders in a dwelling?' WHERE id = 'irc-120' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Wood columns must not be less than what nominal size unless approved or otherwise engineered?' WHERE id = 'irc-121' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The ends of each floor joist, beam or girder bearing on wood or metal must have not less than how much bearing length?' WHERE id = 'irc-122' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Joists framing into the side of a wood girder must be supported by what?' WHERE id = 'irc-123' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The allowable spans for floor joists are based on which design live load conditions?' WHERE id = 'irc-124' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The materials used in the construction of permanent wood foundation walls must be what?' WHERE id = 'irc-126' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The minimum thickness of a concrete foundation wall is generally determined by what factors?' WHERE id = 'irc-128' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Vertical reinforcement in a concrete foundation wall, where required, must have minimum concrete cover of how much measured from the inside face?' WHERE id = 'irc-129' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Sill plates and wall plates anchoring to a concrete or masonry foundation must have anchor bolts spaced not more than how far apart?' WHERE id = 'irc-130' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Anchor bolts attaching the sill plate must extend a minimum of how far into concrete or grouted masonry?' WHERE id = 'irc-131' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A plate washer is required between the sill plate and the nut on each anchor bolt where required by the braced wall provisions. What is the minimum plate washer size?' WHERE id = 'irc-132' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The size of a footing supporting an isolated pier or column is primarily determined by what?' WHERE id = 'irc-133' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'In areas where the probability of termite infestation is very heavy, which of the following is an approved method of protection?' WHERE id = 'irc-134' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'For foam plastic protection, foam plastic insulation is generally restricted from being installed in which location in very heavy termite areas?' WHERE id = 'irc-135' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Wood floor joists closer than what distance to exposed ground in crawl spaces must be naturally durable or preservative-treated wood?' WHERE id = 'irc-136' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Wood in direct contact with the ground or fresh water and supporting permanent structures must be what?' WHERE id = 'irc-137' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Fasteners and connectors in contact with preservative-treated and fire-retardant-treated wood must be what?' WHERE id = 'irc-138' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A lapped, nonsoldered seam metal roof panel installed WITHOUT applied lap sealant requires a minimum roof slope of what?' WHERE id = 'irc-139' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Metal roof shingles shall not be installed on a roof slope less than which of the following?' WHERE id = 'irc-140' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Clay and concrete roof tile shall not be installed on a roof slope less than which value (with double underlayment required for lower slopes)?' WHERE id = 'irc-141' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Wood shingles shall not be installed on a roof slope less than which of the following?' WHERE id = 'irc-142' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Wood shakes shall not be installed on a roof slope less than which of the following?' WHERE id = 'irc-143' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Slate and slate-type shingles shall not be installed on a roof slope less than which of the following?' WHERE id = 'irc-144' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Slate shingles must be fastened with what type of nails?' WHERE id = 'irc-145' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Underlayment for asphalt shingles, metal roof shingles, slate, wood shingles and wood shakes must be applied in accordance with what?' WHERE id = 'irc-146' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'An automatic residential fire sprinkler system, where adopted, is required to be installed in one- and two-family dwellings in accordance with which standard(s)?' WHERE id = 'irc-147' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Per the residential sprinkler standard, sprinklers may generally be omitted from which space?' WHERE id = 'irc-148' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'An emergency escape and rescue opening with a sill below grade must be provided with a window well having a minimum horizontal area of what?' WHERE id = 'irc-149' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A window well with a vertical depth greater than what dimension must be equipped with a permanently affixed ladder or steps?' WHERE id = 'irc-150' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The rungs of a window well ladder must have an inside width of at least how much and be spaced no more than how far apart vertically?' WHERE id = 'irc-151' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Vinyl siding must be fastened so that what condition is met?' WHERE id = 'irc-152' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Exterior wall coverings such as fiber cement, wood and hardboard siding must be installed over what, in addition to the structure?' WHERE id = 'irc-153' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Fiber-cement lap siding having a maximum width of 12 inches must be lapped a minimum of how much?' WHERE id = 'irc-154' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A water-resistive barrier behind the exterior wall covering must consist of at least what?' WHERE id = 'irc-155' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The water-resistive barrier must be applied in what manner to properly shed water?' WHERE id = 'irc-156' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The air space clearance between a masonry chimney located entirely outside the exterior walls and combustible material must be at least how much?' WHERE id = 'irc-157' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The required air-space clearance between a masonry chimney and combustible trim or framing may be reduced or eliminated only when what condition is met?' WHERE id = 'irc-158' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Headers and girders supporting floor and roof loads over openings in load-bearing walls must be sized according to what?' WHERE id = 'irc-159' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The size, height and spacing of studs in a permanent wood foundation wall (and the thickness of supporting plywood) must be determined based on what?' WHERE id = 'irc-160' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Metal roof panels and shingles must be attached so they resist what primary load?' WHERE id = 'irc-161' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Columns must be restrained against what at the bottom end where they bear on a footing or pier?' WHERE id = 'irc-162' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The ladder or steps required for a deep window well are permitted to encroach into the required minimum well dimension by not more than how much?' WHERE id = 'irc-163' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The bracing method designated ''WSP'' refers to which of the following?' WHERE id = 'irc-164' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The bracing method abbreviation ''LIB'' identifies which method?' WHERE id = 'irc-165' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The ''PFH'' continuous method is what type of braced wall panel?' WHERE id = 'irc-166' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What is the maximum spacing permitted between braced wall lines in most conventional light-frame construction?' WHERE id = 'irc-167' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The minimum length of a braced wall panel using continuous wood structural panel sheathing (CS-WSP) is generally based on which factor?' WHERE id = 'irc-168' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Winder treads must have a minimum tread depth of 6 inches at any point and not less than what depth at the walkline?' WHERE id = 'irc-169' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A spiral stairway must have a clear walking width of at least 26 inches and a minimum tread depth of 6-3/4 inches at the walkline located what distance from the narrower edge?' WHERE id = 'irc-170' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The minimum headroom in all parts of a stairway must not be less than which dimension, measured vertically from the sloped line of tread nosings?' WHERE id = 'irc-171' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Guards and handrails must be designed to resist a single concentrated load of how many pounds applied in any direction along the top?' WHERE id = 'irc-172' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'For a 1-story dwelling with conventional light-frame construction on soil with a load-bearing value of 1,500 psf, the minimum footing width is generally what?' WHERE id = 'irc-173' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The minimum thickness for a concrete footing supporting walls of light-frame construction is generally not less than what?' WHERE id = 'irc-174' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Footings must be placed below the frost line or otherwise protected from frost. In Massachusetts, which has a deep design frost depth, this means footings are typically placed at what minimum depth?' WHERE id = 'irc-175' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What is the minimum electrical service rating required for a one-family dwelling?' WHERE id = 'irc-176' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'When a metal underground water pipe is used as a grounding electrode, it must be supplemented by an additional electrode and must be in direct contact with the earth for not less than how many feet?' WHERE id = 'irc-177' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A ground rod electrode (rod and pipe type) must have a length in contact with the soil of not less than what?' WHERE id = 'irc-178' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A 20-ampere branch circuit using copper conductors generally requires what minimum conductor size?' WHERE id = 'irc-179' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'What volume allowance (in cubic inches) is assigned to each 14 AWG conductor when calculating box fill?' WHERE id = 'irc-180' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'At least one wall switch-controlled lighting outlet must be installed in which of the following spaces?' WHERE id = 'irc-181' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'GFCI protection is required for 125-volt, single-phase, 15- and 20-ampere receptacles in which of the following dwelling locations?' WHERE id = 'irc-182' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'AFCI (arc-fault circuit-interrupter) protection is required for 120-volt, 15- and 20-ampere branch circuits supplying outlets in which dwelling areas?' WHERE id = 'irc-183' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A residential water closet (1.6 gpf) is assigned how many drainage fixture units (DFU)?' WHERE id = 'irc-184' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Factory-built fireplaces must be listed and labeled and installed in accordance with what?' WHERE id = 'irc-196' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Factory-built chimneys serving factory-built fireplaces must be listed and labeled and tested to which standard?' WHERE id = 'irc-197' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The firebox of a masonry fireplace must have a minimum depth (front to back) of how much for fireboxes 6 square feet or less in opening?' WHERE id = 'irc-198' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The firebox walls (lining) of a masonry fireplace lined with firebrick must be not less than what thickness?' WHERE id = 'irc-199' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The floor surface of a garage must be of approved noncombustible material, and the area of floor used for parking must be sloped to facilitate movement of liquids toward what?' WHERE id = 'irc-202' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Carports and garages must NOT open directly into which of the following rooms?' WHERE id = 'irc-203' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The minimum thickness of gypsum board used as a ''GB'' braced wall panel applied to each face is what?' WHERE id = 'irc-204' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'The minimum headroom for a spiral stairway, measured vertically from the tread nosings, must be not less than what?' WHERE id = 'irc-205' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Under the small-conductor overcurrent rules, a 15-ampere branch circuit using copper conductors must be wired with at least what conductor size?' WHERE id = 'irc-206' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'A single yoke (strap) supporting one or more devices counts as how many conductor volume allowances, based on the largest conductor connected to the device?' WHERE id = 'irc-207' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Increasing the number of stories on a dwelling generally has what effect on the minimum required footing width (all else equal)?' WHERE id = 'irc-208' AND category = 'IRC';
UPDATE public.quiz_questions SET question = 'Guard in-fill components (such as balusters and panel fillers below the top rail) must be designed to resist a horizontally applied normal load of how many pounds on an area of 1 square foot?' WHERE id = 'irc-210' AND category = 'IRC';
COMMIT;
